image:
  name: docker/compose:3.8

stages:
  - build

before_script:
  - docker version
  - docker-compose version

build:
  stage: build
  script:
    - ls -lah
    - cd backend && docker-compose build
    - cd tg_bot && docker-compose build
    - echo "Build was successful"
  only:
    - gitlab-ci-0.0.1
  tags:
    - hetzner-cloud
