image:
  name: docker

stages:
  - build
  - deploy

before_script:
  - docker version
  - docker compose version

build:
  stage: build
  script:
    - ls -lah
    - docker compose -f backend/docker-compose.yaml build
    - docker compose -f tg_bot/docker-compose.yaml build
    - echo "Build was successful"
  only:
    - main
  tags:
    - hetzner-cloud


deploy:
  stage: deploy
  script:
    - docker compose -f backend/docker-compose.yaml up -d
    - docker compose -f tg_bot/docker-compose.yaml up -d
  only:
    - main
  tags:
    - hetzner-cloud
  when: manual


# TODO: Добавить джобы: линтинга при изменении кода, тестового билда при изменении docker-файлов и тд