image:
  name: docker/compose:latest

stages:
  - build

variables:
   DOCKER_HOST: "tcp://docker:2375"

before_script:
  - docker version
  - docker compose version

build:
  stage: build
  script:
    - docker compose -f backend/docker-compose.yaml build
    - echo "Build was successful"
  only:
    - gitlab-ci-0.0.1
  tags:
    - hetzner-cloud
