services:
  - docker:dind

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker compose -f backend/docker-compose.yaml build
    - echo "Build was succesful"
  only:
    - gitlab-ci-0.0.1


deploy:
  stage: deploy
  script:
    - docker-compose up -d
  only:
    - gitlab-ci-0.0.1
  when: manual
