image:
  name: docker/compose:latest

services:
  - name: docker:dind
    alias: docker

stages:
  - build

before_script:
  - docker version
  - docker-compose version

build:
  stage: build
  script:
    - docker compose -f backend/docker-compose.yaml build
    - echo "Build was succesful"
  only:
    - gitlab-ci-0.0.1
  tags:
    - hetzner-cloud
