version: '3.8'

services:
  api:
    build:
      context: ./
      dockerfile: docker/api/Dockerfile
    hostname: backend_api
    networks:
      - common_network
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    build:
      context: ./
      dockerfile: docker/postgresql/Dockerfile
    networks:
      - common_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    hostname: backend_postgres
    command: postgres -c shared_preload_libraries=pg_cron
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local

networks:
  common_network:
    name: common_network
