version: '3.8'

services:
  api:
    build:
      context: ./
      dockerfile: docker/api/Dockerfile
    networks:
      common_network:
        - ipv4_address: 192.168.0.1
    ports:
      - "127.0.0.1::8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    build:
      context: ./
      dockerfile: docker/postgresql/Dockerfile
    networks:
      common_network:
        - ipv4_address: 192.168.0.2
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    hostname: backend_postgres
    command: postgres -c shared_preload_libraries=pg_cron
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local

networks:
  common_network:
    name: common_network
    ipam:
      config:
        - subnet: "192.168.0.0/24"
