version: '3.1'

services:
  db:
    container_name: postgres
    build:
      context: ./
      dockerfile: docker/postgresql/postgresql.Dockerfile
    command: postgres -c shared_preload_libraries=pg_cron
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
