"""Исправления в user. Добавлено referral.created_at

Revision ID: 08be2b3c47b9
Revises: ede678fe4a48
Create Date: 2023-06-17 23:21:57.876133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08be2b3c47b9'
down_revision = 'ede678fe4a48'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referrals', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_referrals_created_at'), 'referrals', ['created_at'], unique=False)
    op.execute('ALTER TABLE users ADD COLUMN create_time_holder TIMESTAMP without time zone NULL')
    op.execute('ALTER TABLE users ALTER COLUMN subscription_end_date TYPE timestamp without time zone USING create_time_holder')
    op.execute('ALTER TABLE users DROP COLUMN create_time_holder')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_referrals_created_at'), table_name='referrals')
    op.drop_column('referrals', 'created_at')
    # ### end Alembic commands ###
