"""Добавлена таблица лимитов

Revision ID: 10d0409b776c
Revises: 8b0411711a52
Create Date: 2023-06-28 02:17:02.281584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10d0409b776c'
down_revision = '8b0411711a52'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('limits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('free_requests_count', sa.SmallInteger(), nullable=False),
    sa.Column('total_requests_count', sa.SmallInteger(), nullable=True),
    sa.Column('daily_requests_count', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['telegram_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_index(op.f('ix_limits_id'), 'limits', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_limits_id'), table_name='limits')
    op.drop_table('limits')
    # ### end Alembic commands ###
