"""Изменение таблицы лимитов(сокращено кол-во полей)

Revision ID: 2aba664e93d3
Revises: cb95394e547a
Create Date: 2023-07-08 01:34:57.870313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aba664e93d3'
down_revision = 'cb95394e547a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('limits', 'total_requests_count')
    op.drop_column('limits', 'available_requests_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('limits', sa.Column('available_requests_count', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.add_column('limits', sa.Column('total_requests_count', sa.SMALLINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
