"""Убрана лишняя связь user-reviews

Revision ID: 2c83c258aca5
Revises: 5f7424f44f88
Create Date: 2023-07-08 23:41:24.203537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c83c258aca5'
down_revision = '5f7424f44f88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
