"""Добавлено поле reviews.goods_url

Revision ID: 5a0740b3c451
Revises: 2c83c258aca5
Create Date: 2023-07-11 12:02:34.922052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a0740b3c451'
down_revision = '2c83c258aca5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('goods_url', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'goods_url')
    # ### end Alembic commands ###
