"""Тип goods_id изменён на bigint

Revision ID: c4b5b97d5041
Revises: 5a0740b3c451
Create Date: 2023-07-23 00:44:23.799856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4b5b97d5041'
down_revision = '5a0740b3c451'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
