"""Добавлено поле available_requests_count

Revision ID: cb95394e547a
Revises: 10d0409b776c
Create Date: 2023-06-29 04:04:32.266730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb95394e547a'
down_revision = '10d0409b776c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('limits', sa.Column('available_requests_count', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('limits', 'available_requests_count')
    # ### end Alembic commands ###
