"""Добавлена связь One To Many user->joint_purchase_request(односторонняя)

Revision ID: d741067358c5
Revises: 08be2b3c47b9
Create Date: 2023-06-18 01:56:08.149947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd741067358c5'
down_revision = '08be2b3c47b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'joint_purchase_request', 'users', ['chat_id'], ['telegram_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'joint_purchase_request', type_='foreignkey')
    # ### end Alembic commands ###
