"""ручная смена типа goods_id на big int

Revision ID: e9966e15bddf
Revises: 992fc7037940
Create Date: 2023-07-28 15:49:24.083585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9966e15bddf'
down_revision = '992fc7037940'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        table_name='joint_purchase_request',
        column_name='goods_id',
        existing_type=sa.Integer(),
        type_=sa.BigInteger()
    )
    op.alter_column(
        table_name='reviews',
        column_name='goods_id',
        existing_type=sa.Integer(),
        type_=sa.BigInteger()
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        table_name='joint_purchase_request',
        column_name='goods_id',
        existing_type=sa.BigInteger(),
        type_=sa.Integer()
    )
    op.alter_column(
        table_name='reviews',
        column_name='goods_id',
        existing_type=sa.BigInteger(),
        type_=sa.Integer()
    )
    # ### end Alembic commands ###
